# Generated by Django 4.2.29 on 2026-03-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_alter_door_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='category',
            field=models.CharField(help_text='One or more categories, comma-separated', max_length=200),
        ),
        migrations.AlterField(
            model_name='door',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line'),
        ),
        migrations.AlterField(
            model_name='door',
            name='height',
            field=models.CharField(help_text='One or more heights, comma-separated', max_length=200),
        ),
        migrations.AlterField(
            model_name='door',
            name='material',
            field=models.CharField(choices=[('hard_wood', 'Hard Wood'), ('engineered_wood', 'Engineered Wood'), ('steel', 'Steel'), ('glass', 'Glass & Wood'), ('fiber', 'Fiber'), ('pvc', 'PVC'), ('aluminium', 'Aluminium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='door',
            name='price_max',
            field=models.PositiveIntegerField(blank=True, help_text='Deprecated — no longer used. Kept for data migration only.', null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='price_min',
            field=models.PositiveIntegerField(blank=True, help_text='Pooja Room doors only — price in ₹', null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='thickness',
            field=models.CharField(help_text='One or more thicknesses, comma-separated', max_length=200),
        ),
        migrations.AlterField(
            model_name='door',
            name='width',
            field=models.CharField(help_text='One or more widths, comma-separated', max_length=200),
        ),
    ]
