# Generated by Django 4.2.29 on 2026-03-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0003_alter_door_category_alter_door_features_and_more'),
        ('doors', 'migration_fix'),
    ]

    operations = [
    ]
